# Generated by Django 4.2.4 on 2023-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_notes_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.IntegerField(default=1998),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='number_plate',
            field=models.CharField(default='b-100-abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(default='wjdfi2749fkdjwk38', max_length=255),
            preserve_default=False,
        ),
    ]
