# Generated by Django 4.2.4 on 2023-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_car_colour_car_engine_displacement_car_number_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbill',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='productbill',
            name='percent_added',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
