# Generated by Django 4.2.4 on 2023-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_productbill_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbill',
            name='purchasing_price',
        ),
        migrations.AddField(
            model_name='product',
            name='purchasing_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
