# Generated by Django 4.2.4 on 2023-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_productbill_purchasing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date_emitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='series',
            field=models.CharField(default='ODC', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Str. mea', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='cif',
            field=models.CharField(default='RO12354', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='reg_com',
            field=models.CharField(default='J12/256/2000', max_length=50),
            preserve_default=False,
        ),
    ]
