# Generated by Django 4.2.4 on 2023-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bill_estimate_number_bill_repairing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
